openapi: 3.0.3
info:
  title: Egon Viz API
  version: 0.0.1
tags:
  - name: pipeline
    description: The structure and status of a running pipeline
paths:
  /pipeline/:
    get:
      summary: Return pipeline data by ID
      description: Returns information for a currently running pipeline
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
        '401':
          description: Access token is missing or invalid
        '404':
          description: A running pipeline was not found with the given ID
components:
  schemas:
    Pipeline:
      required:
        - id
        - name
        - nodes
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: My Pipeline
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
    Node:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          example: Extract