openapi: 3.0.3
info:
  title: Egon Status API
  version: 0.0.1
  contact:
    url: https://github.com/Egon-Framework/status-api
  description: |-
    ## API Overview
    
    The status API is a small, read-only API for monitoring Egon pipelines.
    API endpoints are broken into two categories based on general use case.
    
    **API Status** endpoints are provided for checking API health, version, and documentation.
    These endpoints provide no information about running Egon processes and can be accessed without authentication.
    
    **Pipeline Metadata** endpoints expose information about user submitted Egon pipelines.
    These endpoints are authenticated via API tokens.
    Each token is tied to an individual pipeline and provides access to information about a single running pipeline.
    Tokens are valid for the life-time of the associated pipeline and expire once the pipeline is no longer running.
servers:
  - url: https://{url}:{port}/V0
    description: Local development server
    variables:
      url:
        default: localhost
        description: The base API URL
      port:
        default: '4010'
        description: The API port number
tags:
  - name: API Status
    description: Retrieve information concerning the API's health and version
  - name: Pipeline Metadata
    description: Metadata and status information for currently running pipeline components
paths:
  /:
    get:
      tags:
        - API Status
      summary: Base API URL
      description: The base API URL points users at the API documentation.
      operationId: root
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: 'The Egon Framework status API. See https://egon-framework.github.io/status-api/ for more details.'
  /health:
    get:
      tags:
        - API Status
      summary: API health check
      description: Check the API health status.
      operationId: healthCheck
      responses:
        '200':
          description: OK
  /version:
    get:
      tags:
        - API Status
      summary: Get the API version
      description: Return the current API version number.
      operationId: version
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
              examples:
                version 0.1:
                  $ref: '#/components/examples/Version'
  /pipeline/{pipelineId}:
    get:
      tags:
        - Pipeline Metadata
      security:
        - TokenQueryAuth: [ ]
      summary: Get pipeline metadata
      description: Get metadata for a currently running pipeline by its ID.
      operationId: getPipelineById
      parameters:
        - name: pipelineId
          in: path
          description: Pipeline ID to return data for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
              examples:
                etl:
                  $ref: '#/components/examples/ETLPipeline'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/MissingResourceError'
  /node/{nodeID}:
    get:
      tags:
        - Pipeline Metadata
      security:
        - TokenQueryAuth: [ ]
      summary: Get node metadata
      description: Get metadata for a single pipeline node by its ID.
      operationId: getNodeById
      parameters:
        - name: nodeID
          in: path
          description: Node ID to return data for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
              examples:
                extract:
                  $ref: '#/components/examples/ExtractNode'
                transform:
                  $ref: '#/components/examples/TransformNode'
                load:
                  $ref: '#/components/examples/LoadNode'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/MissingResourceError'
components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
    MissingResourceError:
      description: Resource not found
  examples:
    Version:
      description: Version 0.1
      value:
        version: "0.1"
    ETLPipeline:
      summary: A generic ETL Pipeline
      value:
        id: "57d92d7e-58c0-48ec-bed2-2e8b507161bb"
        name: ETL Pipeline
        description: An ETL pipeline with three nodes
        launched: 2020-07-21T17:32:28Z
        status: running
        nodes: [
          {
            node: 760c45a4-9a65-418f-a442-aa8c3f22cad2,
            downstream: [ 1da5a095-00af-45fe-ba1b-ea9576439f75 ]
          },{
            node: 1da5a095-00af-45fe-ba1b-ea9576439f75,
            downstream: [ ae3de17e-1c7a-4817-b619-b5aa984ffe51 ]
          },{
            node: ae3de17e-1c7a-4817-b619-b5aa984ffe51,
            downstream: [ ]
          },
        ]
    ExtractNode:
      summary: Extract node for an ETL pipeline
      value:
        id: 760c45a4-9a65-418f-a442-aa8c3f22cad2
        name: Extract
        description: Load data into the pipeline
        instances: 1
        status: stopped
    TransformNode:
      summary: Transform node in an ETL pipeline
      value:
        id: 1da5a095-00af-45fe-ba1b-ea9576439f75
        name: Transform
        description: Transform and analyze pipeline data
        instances: 4
        status: running
    LoadNode:
      summary: The load step in an ETL pipeline
      value:
        id: ae3de17e-1c7a-4817-b619-b5aa984ffe51
        name: Load
        instances: 2
        status: running
  schemas:
    Version: # The API version number
      required:
        - version
      properties:
        version:
          type: string
          pattern: ^\d*\.\d*$
      example:
        $ref: '#/components/examples/Version/value'
    Node: # Meta data for a given node
      required:
        - id
        - name
        - instances
        - status
      type: object
      properties:
        id:
          type: string
          pattern: ^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$ # UUID4 format
        name:
          type: string
        description:
          type: string
        instances:
          type: integer
        status:
          type: string
          enum: [ 'launching', 'running', 'stopped', 'degraded', 'errored', 'unknown' ]
      example:
        $ref: '#/components/examples/ExtractNode/value'
    Pipeline: # Meta data for a given pipeline
      required:
        - id
        - name
        - description
        - launched
        - status
        - nodes
      type: object
      properties:
        id:
          type: string
          pattern: ^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$ # UUID4 format
        name:
          type: string
        description:
          type: string
        launched:
          type: string
          format: date-time
          pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$
        status:
          type: string
          enum: [ 'launching', 'running', 'stopped', 'degraded', 'errored', 'unknown' ]
        nodes: # Mapping of pipeline node IDs to downstream node IDs
          type: array
          items:
            type: object
            required:
              - node
              - downstream
            properties:
              node:
                type: string
                pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$
              downstream:
                type: array
                items:
                  type: string
                  pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$
                uniqueItems: true
      example:
        $ref: '#/components/examples/ETLPipeline/value'
  securitySchemes:
    TokenQueryAuth:
      type: apiKey
      in: query
      name: User Token
      description: |-
        Credentials generated under this category are temporary and limited in scope.
        User tokens provide access to information concerning a single running pipeline.
        Once the associated pipeline is no longer running, the credentials expire.
